modLoader="javafml"
loaderVersion="[45,)"
license="Mozilla Public License 2.0"

[[mods]]
modId="musithy"
version="1.0.0"
displayName="Musithy"
credits="Suluntulu"
displayURL="https://mcreator.net"
authors="FishyHard"

[[dependencies.musithy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"



[[dependencies.musithy]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

