modLoader="javafml"
loaderVersion="[47,)"
license="Mozilla Public License 2.0"

[[mods]]
modId="musithy"
version="1.0.0"
displayName="Musithy"
displayURL="https://modrinth.com/project/musithy https://legacy.curseforge.com/minecraft/mc-mods/musithy"
credits="Suluntulu"
authors="FishyHard"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.musithy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.musithy]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration